version: "3.7"
networks:
  prometheus:
    external: true

volumes:
  promfik:

services:
  traefik:
    image: traefik:1.7
    command: --api --docker --docker.swarmmode --docker.watch --debug=false --metrics.prometheus=true --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prometheus
    ports:
      - 80:80
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.docker.network=prometheus"

  whoami:    
    image: jwilder/whoami
    networks:
      - prometheus
    deploy:
      labels:
        - traefik.port=8000
        - traefik.backend=whoami
        - traefik.frontend.rule=Host:whoami.localhost
        - "traefik.enable=true"
        - "traefik.docker.network=prometheus" 

  tech:    
    image: handuy1992/calc
    networks:
      - prometheus
    deploy:
      labels:
        - traefik.port=3000
        - traefik.backend=tech
        - traefik.frontend.rule=Host:tech.localhost
        - "traefik.enable=true"
        - "traefik.docker.network=prometheus"

  prometheus:    
    image: prom/prometheus
    networks:
      - prometheus
    volumes:
      - ./prom.yml:/etc/prometheus/prometheus.yml
      - promfik:/prometheus
    deploy:
      labels:
        - traefik.port=9090
        - traefik.backend=prometheus
        - traefik.frontend.rule=Host:prometheus.localhost
        - "traefik.enable=true"
        - "traefik.docker.network=prometheus" 